name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.5,3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/tests.txt
    - name: Test with pytest
      run: |
        PYTHONPATH=. pytest janis_core/tests/test_*.py -m "not release"
    - uses: codecov/codecov-action@v2
